const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';
const UPDATE_LOGIN_TEXT = 'UPDATE_LOGIN_TEXT';
const UPDATE_LOGIN_ICON = 'UPDATE_LOGIN_ICON';
const SUBMIT_LOGIN_DIALOG = 'SUBMIT_LOGIN_DIALOG';
const OPEN_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG';
const UPDATE_CREATE_TEXT = 'CREATE_TEXT_CHANGE';
const SUBMIT_CREATE_DIALOG = 'SUBMIT_CREATE_DIALOG';
const TOGGLE_FEEDBACK_MINI_MENU = 'TOGGLE_FEEDBACK_MINI_MENU';
const TOGGLE_FEEDBACK_RATING = 'TOGGLE_FEEDBACK_RATING';
const REMOVE_FEEDBACK = 'REMOVE_FEEDBACK';

export {CLOSE_LOGIN_DIALOG, UPDATE_LOGIN_TEXT, UPDATE_LOGIN_ICON, SUBMIT_LOGIN_DIALOG, OPEN_CREATE_DIALOG, CLOSE_CREATE_DIALOG, UPDATE_CREATE_TEXT, SUBMIT_CREATE_DIALOG, TOGGLE_FEEDBACK_MINI_MENU, TOGGLE_FEEDBACK_RATING, REMOVE_FEEDBACK};
