const OPEN_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG';
const SUBMIT_CREATE_DIALOG = 'SUBMIT_CREATE_DIALOG';
const TOGGLE_FEEDBACK_MINI_MENU = 'TOGGLE_FEEDBACK_MINI_MENU';

export {OPEN_CREATE_DIALOG, CLOSE_CREATE_DIALOG, SUBMIT_CREATE_DIALOG, TOGGLE_FEEDBACK_MINI_MENU};
