const loginActions = {
    OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
    CLOSE_LOGIN_DIALOG: 'CLOSE_LOGIN_DIALOG',
    UPDATE_LOGIN_NAME: 'UPDATE_LOGIN_NAME',
    UPDATE_LOGIN_ICON: 'UPDATE_LOGIN_ICON',
    UPDATE_LOGIN_USER_ID: 'UPDATE_LOGIN_USER_ID',
    SUBMIT_LOGIN_DIALOG: 'SUBMIT_LOGIN_DIALOG'
};

const createActions = {
    TOGGLE_CREATE_OPTIONS: 'TOGGLE_CREATE_OPTIONS',
    OPEN_CREATE_DIALOG: 'OPEN_CREATE_DIALOG',
    CLOSE_CREATE_DIALOG: 'CLOSE_CREATE_DIALOG',
    UPDATE_CREATE_TEXT: 'CREATE_TEXT_CHANGE',
    SUBMIT_CREATE_DIALOG: 'SUBMIT_CREATE_DIALOG'
};

const feedbackActions = {
    TOGGLE_FEEDBACK_OPTIONS: 'TOGGLE_FEEDBACK_OPTIONS',
    TOGGLE_FEEDBACK_RATING: 'TOGGLE_FEEDBACK_RATING',
    ADD_FEEDBACK: 'ADD_FEEDBACK',
    REMOVE_FEEDBACK: 'REMOVE_FEEDBACK',
    EDIT_FEEDBACK: 'EDIT_FEEDBACK',
    UPDATE_THIS_USER_FEEDBACK: 'UPDATE_THIS_USER_FEEDBACK'
};

export default {
    ...loginActions,
    ...createActions,
    ...feedbackActions
};
