const OPEN_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG';
const SUBMIT_CREATE_DIALOG = 'SUBMIT_CREATE_DIALOG';

export {OPEN_CREATE_DIALOG, CLOSE_CREATE_DIALOG, SUBMIT_CREATE_DIALOG};
